# Generated by Django 5.1.7 on 2025-03-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("descricao", models.TextField(blank=True, max_length=200, null=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, max_length=500, null=True)),
                ("preco", models.PositiveBigIntegerField(null=True)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ManyToManyField(blank=True, to="produto.categoria"),
                ),
            ],
        ),
    ]
