name: Deploy para Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Configura ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Instala dependencias Python
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executa coleta de arquivos estaticos e migracoes
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate

      - name: Deploy p/ Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
